# If mysql is disabled, the plugin will store everything in a json file
mysql:
  enabled: false
  address: '127.0.0.1'
  port: 3306
  database: minecraft
  username: root
  password: ''
messages:
  test: "This is a test"